### ISSUE TITLE
Sylius 1.6 support

### ISSUE THREAD

**Issue by damonsson** [webgriffe/WebgriffeSyliusTableRateShippingPlugin#1]
Any plans to support Sylius 1.6? Any knowns incompatibilities with 1.6?

**Comment by mmenozzi** [comment]
We never tested on 1.6 but I don’t think there will be any incompatibilities. Would you like to give it a try?

**Comment by damonsson** [comment]
Sure, will try it, because we need it in one project on 1.6. Thanks for the fast answer!

**Comment by mmenozzi** [comment]
Cool! Let us know how it will go!
