### ISSUE TITLE
json_array type is removed from doctrine dbal 3+

### ISSUE THREAD

**Issue by laurentdabbb** [webgriffe/WebgriffeSyliusTableRateShippingPlugin#12]
Hi,

You should replace "json_array" type by "json" type for the **weightLimitToRate** field.

"json_array" type is deprecated from doctrine dbal 2.6+ and removed from 3+.

https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/types.html#json-array

Same problem on Sylius : [#13211](https://github.com/Sylius/Sylius/issues/13211)

Thx

**Comment by mmenozzi** [comment]
Closed with #13
