### ISSUE TITLE
Template bug on Sylius 1.7 ?

### ISSUE THREAD

**Issue by Bastienbretenet** [webgriffe/WebgriffeSyliusTableRateShippingPlugin#2]
Hi, 

After installing on Sylius 1.7, I had a problem to admin view . The form collection doesnt  work (see attach files at the end) . 

To resovle this, I change 2 files : 

- update.html.twig -> line 3 : 
`
{% form_theme form.weightLimitToRate '@WebgriffeSyliusTableRateShippingPlugin/TableRateCrud/_weightLimitToRateTheme.html.twig' %}
`
To join on new template reference.

- _weightLimitToRateTheme.html.twig -> line 12 - 23 : 

`<div data-form-type="collection" {{ block('widget_container_attributes') }}
            {% if prototype is defined and allow_add %}
                data-prototype='{{ self.collection_item(prototype, allow_delete, button_delete_label, prototype.vars.name)|e }}'
                data-prototype-name='{{ prototype.vars.name }}'
            {%- endif -%}
        >
            {{ error(form.vars.errors) }}
            {% if prototypes|default is iterable %}
                {% for key, subPrototype in prototypes %}
                    <input type="hidden" data-form-prototype="{{ key }}"
                           value="{{ self.collection_item(subPrototype, allow_delete, button_delete_label, subPrototype.vars.name)|e }}"
                           data-subprototype-name="{{ subPrototype.vars.name }}"
                    />
                {% endfor %}
            {% endif %}`
Create a new file on theme or template.

I think that the new JS code on admin (Sylius\Bundle\UiBundle\Resources\private\js\sylius-form-collection.js) need " data-prototype-name  " to run correctly. 

Isn't perfect but it works... 

Maybe add new views to work on Sylius 1.7 ? 

Thank you.

Before
![TableRateShipping-before](https://user-images.githubusercontent.com/40366750/84281194-91271f80-ab38-11ea-8316-fbe68e326615.PNG)

After
![TableRateShipping-after](https://user-images.githubusercontent.com/40366750/84281190-908e8900-ab38-11ea-8b2e-3b2aac444fa9.PNG)

**Comment by mmenozzi** [comment]
Hi @Bastienbretenet, sorry for the late reply.
This plugin hasn't been really tested on 1.7.
Indeed we have the `~1.4.0` version constraint in the `composer.json`.

I'm going to open a new issue about the 1.7 upgrade for this plugin referencing this issue in it.

Thank you!
