### ISSUE TITLE
Adding Price rate table

### ISSUE THREAD

**Issue by Roshyo** [webgriffe/WebgriffeSyliusTableRateShippingPlugin#6]
This is a feature request : 

What do you think about adding a Price table rate ?

The use case would be : 
With `x` shipping method, the shipment is free above `300€` 
With `y` shipping method, the shipment is free above `500€`

**Comment by mmenozzi** [comment]
No I don't think is a feature for this plugin...
If you add a new rule type about the shipping method I think it's already possible to do this with the promo engine.
