### ISSUE TITLE
Error after composer require

### ISSUE THREAD

**Issue by Snowbaha** [webgriffe/WebgriffeSyliusTableRateShippingPlugin#9]
Hello,

Juste after the composer require, there is a trouble
![image](https://user-images.githubusercontent.com/3284722/115687812-d3c1a700-a35a-11eb-9530-e99f3d3ef31f.png)

so you have to quick add the line:
`- { resource: "@WebgriffeSyliusTableRateShippingPlugin/Resources/config/config.yml" }`
before the end of the composer command

Maybe fix it or change the doc? ^^

**Comment by mmenozzi** [comment]
Official Sylius plugins solves this issue with a [Symfony Flex contrib recipe](https://github.com/symfony/recipes-contrib/blob/master/sylius/invoicing-plugin/0.5/config/packages/sylius_invoicing.yaml).

I think that we can just fix the doc instead.

**Comment by mmenozzi** [comment]
Closed in https://github.com/webgriffe/WebgriffeSyliusTableRateShippingPlugin/commit/5bc2bdb54d6c758d43b99a9b36a1cc2dbd71523d

**Comment by Snowbaha** [comment]
ok no problem, thanks!
